### ISSUE TITLE
igvShiny options$genomeName='local' or 'remote'

### ISSUE THREAD

**Issue by JAMKuttan** [paul-shannon/igvShiny#26] opened 2022-05-04 22:18 UTC
I cant seem to get anything to actually show when my IGV is rendered. The logs seem to be correct, but nothing is outputed as a reference.

output$igvShiny_0 <- renderIgvShiny({
    igvShiny(options = list(genomeName = "local",
                            fasta = "/Users/jerem/Pipelines/nf-crisprdesign/vizapp/loxAfr3/Loxodonta_africana.loxAfr3.dna.toplevel.fa",
                            index = "/Users/jerem/Pipelines/nf-crisprdesign/vizapp/loxAfr3/Loxodonta_africana.loxAfr3.dna.toplevel.fa.fai",
                            initialLocus="",
                            displayMode = "EXPANDED"))
  })
  
Also, for 'remote' many fastas are kept in gzip format. Could you add the ability to input and read .fa.gz and .fa.gz.fai (example below)

output$igvShiny_0 <- renderIgvShiny({
    igvShiny(options = list(genomeName = "remote",
                            fasta = "http://ftp.ensembl.org/pub/release-106/fasta/homo_sapiens/dna_index/Homo_sapiens.GRCh38.dna.toplevel.fa.gz",
                            index = "http://ftp.ensembl.org/pub/release-106/fasta/homo_sapiens/dna_index/Homo_sapiens.GRCh38.dna.toplevel.fa.gz.fai",
                            initialLocus="",
                            displayMode = "EXPANDED"))
  })

**Comment by paul-shannon** [comment] 2022-05-04 22:24
@JAMKuttan   Thanks for the bug report, sorry for the trouble.

I am refactoring this code at this very moment in a new branch, "customGenome".   Another day's work and it should be ready.  I will include your example in my tests, and either get back to you with questions, or a working example.

**Comment by JAMKuttan** [comment] 2022-05-04 23:05
Thank you very much! I look forward to hearing more! This tool is great by the way! Extremely handy for quick UI spin ups!

**Comment by JAMKuttan** [comment] 2022-05-06 15:48
Hi! So I cannot get my local genome to render on the shinyUI. I get no errors in the code, it just doesnt output any IGV. I suspect its because I use a gtf file in my genomeAnnotation instead of gff3? Is this a requirement?

**Comment by paul-shannon** [comment] 2022-05-06 15:57
You might take a look at your javascript console.  Clarifying error messages can sometimes be found there.

For now, yes: gff3 is all we support.  try setting the annotation field to NA.  your genome should load.

Can you run my examples, both http and localFile versions?

notice that genomeAnnotation defaults to NA: 
```
parseAndValidateGenomeSpec <- function(genomeName, initialLocus="all",
                                      stockGenome=TRUE,
                                      dataMode=NA, fasta=NA, fastaIndex=NA, genomeAnnotation=NA)
```
Also you could send me your files (if dataMode==“localFiles”) or the urls (if dataMode==“http”)

- Paul

**Comment by JAMKuttan** [comment] 2022-05-06 16:22
I cannot get your examples to render either. The app comes up when I run the code, but the page is completely blank. I have tested this in R3 and R4. Both with all the dependencies added.

**Comment by paul-shannon** [comment] 2022-05-06 16:27
@JAMKuttan - sorry for the trouble!   
Can you send me (copy & paste) the contents of your javascript console?
And your R sessionInfo()?

**Comment by JAMKuttan** [comment] 2022-05-06 16:37
> sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] igvShiny_1.4.12        rtracklayer_1.56.0     GenomeInfoDbData_1.2.8 GenomicRanges_1.48.0   GenomeInfoDb_1.32.1    IRanges_2.30.0         S4Vectors_0.34.0      
 [8] BiocGenerics_0.42.0    htmlwidgets_1.5.4      shiny_1.7.1           

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3                lattice_0.20-45             Rsamtools_2.12.0            Biostrings_2.64.0           digest_0.6.29               V8_4.1.0                   
 [7] mime_0.12                   R6_2.5.1                    httr_1.4.3                  zlibbioc_1.42.0             rlang_1.0.2                 curl_4.3.2                 
[13] rstudioapi_0.13             jquerylib_0.1.4             DT_0.22                     Matrix_1.4-1                randomcoloR_1.1.0.1         BiocParallel_1.30.0        
[19] Rtsne_0.16                  stringr_1.4.0               RCurl_1.98-1.6              munsell_0.5.0               DelayedArray_0.22.0         compiler_4.2.0             
[25] httpuv_1.6.5                htmltools_0.5.2             SummarizedExperiment_1.26.1 matrixStats_0.62.0          XML_3.99-0.9                withr_2.5.0                
[31] crayon_1.5.1                later_1.3.0                 GenomicAlignments_1.32.0    bitops_1.0-7                grid_4.2.0                  jsonlite_1.8.0             
[37] xtable_1.8-4                lifecycle_1.0.1             magrittr_2.0.3              scales_1.2.0                cachem_1.0.6                cli_3.3.0                  
[43] stringi_1.7.6               XVector_0.36.0              promises_1.2.0.1            remotes_2.4.2               bslib_0.3.1                 ellipsis_0.3.2             
[49] rjson_0.2.21                restfulr_0.0.13             tools_4.2.0                 Biobase_2.56.0              MatrixGenerics_1.8.0        parallel_4.2.0             
[55] fastmap_1.1.0               yaml_2.3.5                  colorspace_2.0-3            cluster_2.1.3               sass_0.4.1                  BiocIO_1.6.0

**Comment by JAMKuttan** [comment] 2022-05-06 16:38
> runApp('C:/Users/jerem/Pipelines/nf-crisprdesign/vizapp/PSapp.R')
[1] setting height from state

Listening on http://127.0.0.1:5929
[1] --- leaving igvShiny.R, renderIgvShiny
--- starting renderIgvShiny
[1] --- ~/github/igvShiny/R/igvShiny ctor
[1]   initial track count: 0

**Comment by paul-shannon** [comment] 2022-05-06 16:47
@JAMKuttan thank you for your patience with this.   It was my strong wish that no patience from you would be required!

If you have some patience left, please try this:

1. ```cd igvShiny/inst/demos/customGenomes/```
2. ```R -f customGenome-remoteFiles-sars.R```

In the R console you will see:  
```
Listening on http://127.0.0.1:6867
```
3. Go to your web browser
4. Open the javascript console
5. Paste ```http://127.0.0.1:6867``` into your web browser's address box
6. Hit return
Here is what I see:
```
 ---- ~/github/igvShiny/inst/htmlwidgets, renderValue
      el: 
 <div id=​"igvShiny_0" class=​"igvShiny html-widget html-widget-output shiny-bound-output" aria-live=​"polite">​</div>​
 igv.js renderValue, wh: 1832, 0
 --------- options
 {stockGenome: false, dataMode: 'http', validated: true, genomeName: 'SARS-CoV-2', fasta: 'https://igv-data.systemsbiology.net/testFiles/sarsGenome/Sars_cov_2.ASM985889v3.dna.toplevel.fa', …}
 ---- el
 <div id=​"igvShiny_0" class=​"igvShiny html-widget html-widget-output shiny-bound-output" aria-live=​"polite">​</div>​
 igvShiny_0
 fasta: https://igv-data.systemsbiology.net/testFiles/sarsGenome/Sars_cov_2.ASM985889v3.dna.toplevel.fa
 index: https://igv-data.systemsbiology.net/testFiles/sarsGenome/Sars_cov_2.ASM985889v3.dna.toplevel.fa.fai
 about to createBrowser, trackHeight: undefined
 igv.min-2.12.6.js:72 Initial locus not found: all
 createBrowser promise fulfilled
 about to save igv browser
 jqueryTag: #igvShiny_0 .igv-root
  count: 0
 []
```
What do you see?

**Comment by JAMKuttan** [comment] 2022-05-06 17:09
---- ~/github/igvShiny/inst/htmlwidgets, renderValue
igvShiny.js:7      el: 
igvShiny.js:7 <div id=​"igvShiny_0" class=​"igvShiny html-widget html-widget-output shiny-bound-output" aria-live=​"polite">​</div>​
igvShiny.js:7 igv.js renderValue, wh: 1287, 0
igvShiny.js:7 --------- options
igvShiny.js:7 {stockGenome: false, dataMode: 'http', validated: true, genomeName: 'SARS-CoV-2', fasta: 'https://igv-data.systemsbiology.net/testFiles/sarsGenome/Sars_cov_2.ASM985889v3.dna.toplevel.fa', …}
igvShiny.js:7 ---- el
igvShiny.js:7 <div id=​"igvShiny_0" class=​"igvShiny html-widget html-widget-output shiny-bound-output" aria-live=​"polite">​</div>​
igvShiny.js:7 igvShiny_0
igvShiny.js:7 fasta: https://igv-data.systemsbiology.net/testFiles/sarsGenome/Sars_cov_2.ASM985889v3.dna.toplevel.fa
igvShiny.js:7 index: https://igv-data.systemsbiology.net/testFiles/sarsGenome/Sars_cov_2.ASM985889v3.dna.toplevel.fa.fai
igvShiny.js:7 about to createBrowser, trackHeight: undefined

Uncaught ReferenceError: igv is not defined
    at Object.renderValue (igvShiny.js:67:10)
    at Object.renderValue (htmlwidgets.js:886:25)
    at e.shinyBinding.renderValue (htmlwidgets.js:541:20)
    at e.value (outputBinding.ts:48:12)
    at e.delegator.<computed> [as onValueChange] (htmlwidgets.js:112:23)
    at e.value (outputAdapter.ts:38:20)
    at e.value (shinyapp.ts:559:17)
    at e.<anonymous> (shinyapp.ts:736:20)
    at e.value (shinyapp.ts:717:29)
    at e.value (shinyapp.ts:700:12)

**Comment by paul-shannon** [comment] 2022-05-06 17:24
@JAMKuttan - thank you.   I see my error.   I used the latest version of igv.js ```igv.min-2.12.6.js``` but failed to commit that to the repo.    It is there now.  So if you do a fresh pull, you will see this:
```
Unpacking objects: 100% (6/6), 282.46 KiB | 2.43 MiB/s, done.
From https://github.com/paul-shannon/igvShiny
   c9cb183..eea5108  customGenome -> origin/customGenome
Updating c9cb183..eea5108
Fast-forward
 inst/htmlwidgets/lib/igv.min-2.12.6.js | 73 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 73 insertions(+)
 create mode 100644 inst/htmlwidgets/lib/igv.min-2.12.6.js
```
then do a fresh build (```make roxy install```) 
then please try my ```R -f customGenome-remoteFiles-sars.R``` demo again.

**Comment by JAMKuttan** [comment] 2022-05-06 17:35
I can confirm it works now! Both http and localFiles! Thanks so much for your assistance! This tool is great and we love to use it!

**Comment by paul-shannon** [comment] 2022-05-06 17:44
@JAMKuttan - I  am so very glad to hear this.   Thank you for your patience, for helping me figure this out.
  
If you have further requests or (perish the thought!) bug reports, please send them along.

**Comment by JAMKuttan** [comment] 2022-05-11 15:56
Hello. I think I may have misspoke before. For some reason now when I come back to it, I cannot get the local to work. HTTP works great! But local doesn't render anything in the tracks.

**Comment by paul-shannon** [comment] 2022-05-11 15:58
Could you to make sure my local example works?

**Comment by JAMKuttan** [comment] 2022-05-11 16:04
sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] igvShiny_1.4.12        htmlwidgets_1.5.4      rtracklayer_1.56.0     GenomeInfoDbData_1.2.8 GenomicRanges_1.48.0   GenomeInfoDb_1.32.1    IRanges_2.30.0         S4Vectors_0.34.0      
 [9] BiocGenerics_0.42.0    shiny_1.7.1           

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3                lattice_0.20-45             Rsamtools_2.12.0            Biostrings_2.64.0           digest_0.6.29               V8_4.1.0                   
 [7] mime_0.12                   R6_2.5.1                    httr_1.4.3                  zlibbioc_1.42.0             rlang_1.0.2                 curl_4.3.2                 
[13] rstudioapi_0.13             jquerylib_0.1.4             Matrix_1.4-1                randomcoloR_1.1.0.1         BiocParallel_1.30.0         Rtsne_0.16                 
[19] stringr_1.4.0               RCurl_1.98-1.6              munsell_0.5.0               DelayedArray_0.22.0         compiler_4.2.0              httpuv_1.6.5               
[25] htmltools_0.5.2             SummarizedExperiment_1.26.1 matrixStats_0.62.0          XML_3.99-0.9                crayon_1.5.1                withr_2.5.0                
[31] later_1.3.0                 GenomicAlignments_1.32.0    bitops_1.0-7                grid_4.2.0                  jsonlite_1.8.0              xtable_1.8-4               
[37] lifecycle_1.0.1             magrittr_2.0.3              scales_1.2.0                cachem_1.0.6                cli_3.3.0                   stringi_1.7.6              
[43] XVector_0.36.0              promises_1.2.0.1            bslib_0.3.1                 ellipsis_0.3.2              rjson_0.2.21                restfulr_0.0.13            
[49] tools_4.2.0                 Biobase_2.56.0              MatrixGenerics_1.8.0        parallel_4.2.0              fastmap_1.1.0               yaml_2.3.5                 
[55] colorspace_2.0-3            cluster_2.1.3               sass_0.4.1                  BiocIO_1.6.0               





Failed to load resource: the server responded with a status of 404 (Not Found)
igvShiny.js:7 ---- ~/github/igvShiny/inst/htmlwidgets, renderValue
igvShiny.js:7      el: 
igvShiny.js:7 <div id=​"igvShiny_0" class=​"igvShiny html-widget html-widget-output shiny-bound-output" aria-live=​"polite" style=​"visibility:​ inherit;​">​…​</div>​
igvShiny.js:7 igv.js renderValue, wh: 880, 0
igvShiny.js:7 --------- options
igvShiny.js:7 Object
igvShiny.js:7 ---- el
igvShiny.js:7 <div id=​"igvShiny_0" class=​"igvShiny html-widget html-widget-output shiny-bound-output" aria-live=​"polite" style=​"visibility:​ inherit;​">​…​</div>​
igvShiny.js:7 igvShiny_0
igvShiny.js:7 fasta: tracks/Sars_cov_2.ASM985889v3.dna.toplevel.fa
igvShiny.js:7 index: tracks/Sars_cov_2.ASM985889v3.dna.toplevel.fa.fai
igvShiny.js:7 about to createBrowser, trackHeight: undefined
:4994/tracks/Sars_cov_2.ASM985889v3.dna.toplevel.fa.fai:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
127.0.0.1/:1 
        
       Uncaught (in promise) 404
igv.min-2.12.6.js:72 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Hv.Vv (igv.min-2.12.6.js:72:276688)
DevTools failed to load source map: Could not load content for http://127.0.0.1:4994/dom.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:4994/igv-ui.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:4994/circular-view.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
igv.min-2.12.6.js:72 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Hv.Vv (igv.min-2.12.6.js:72:276688)
Vv @ igv.min-2.12.6.js:72

**Comment by JAMKuttan** [comment] 2022-05-11 16:11
Even if I delete the folder and let it reload with the SARS genome files, it still doesn't render even though I can see the tracks folder with the correct files inside.

**Comment by paul-shannon** [comment] 2022-05-11 16:12
sorry for the trouble.  I'm working on this now.   Did the local sars genome example ever work for you?

**Comment by JAMKuttan** [comment] 2022-05-11 16:14
I guess it didnt. I think when I tested last week it was only loading HTTP? Which I can confirm works right now still.

**Comment by paul-shannon** [comment] 2022-05-11 16:26
Please try this:

- do a fresh pull to get igvShiny version 1.4.13
- do a fresh ```make roxy install```
- cd inst/unitTests
-  R -f test_genomeSpec.R   # do all tests pass?  if so, then proceed:
- cd inst/demos/customGenomes
- start R
-  source("customGenome-localFiles-sars.R")
-  runApp(shinyApp(ui, server), port=6867)

**Comment by paul-shannon** [comment] 2022-05-11 17:48
Looks like you may be on the wrong branch.   Here's what you should see:
```
 git branch -v
* customGenome                 56a85ae added ribosomal genome files
  master                       be9b05f latest igv.js
  tracksSpecifiedInConstructor 0722362 igvReady (and igv-igvReady) events sent to R at startup
```

**Comment by JAMKuttan** [comment] 2022-05-11 17:55
I apologize, maybe I misunderstand the backend... But is this not the same result as a full git pull?
remotes::install_github("paul-shannon/igvShiny", ref = "customGenome")

**Comment by paul-shannon** [comment] 2022-05-11 18:03
Perhaps you can also run the unit test suggested above?
```
R -f test_genomeSpec.R 
```

**Comment by JAMKuttan** [comment] 2022-05-11 18:43
Yes I can confirm that the unit tests complete with a TRUE.

**Comment by paul-shannon** [comment] 2022-05-11 18:56
Thank you for your patience @JAMKuttan!  I regret that this is not yet working for you.
If you don't mind a few more experiments, please try:

-  ```ls -l inst/htmlwidgets/lib/igv.min-2.12.6.js```
-  ```file.info(system.file(package="igvShiny", "htmlwidgets", "lib", "igv.min-2.12.6.js"))```
- ```cat inst/htmlwidgets/igvShiny.yaml```

**Comment by JAMKuttan** [comment] 2022-05-11 20:49
All three exist correctly and show igv.min-2.12.6.js

**Comment by ChristianRohde** [comment] 2022-05-14 23:31
Hi, interesting discussion. I freshly downloaded igvShiny (1.4.14) with R version 4.1.3 (2022-03-10) and macOS Monterey 12.3.1. I used force=TRUE to make sure that I really get the latest version: remotes::install_github("paul-shannon/igvShiny", ref = "customGenome", force = TRUE). My own script did not run out of the box any more, so I looked into the details as much as I can. I found that everything seems to depend pretty much on addResourcePath() => I missed to copy this into my previous script before but seemed to have the variable it creates alive in memory from running the 2 example scripts.  You have to restart R to get rid of this variable. Then the path in addResourcePath is basically set to the folder were the scripts are in and the script creates the folder "tracks" in its path. Next, the custom genome is copied from any path you provide to the folder tracks as set in addResourcePath(). And finally both the Sars2 genome as well the small genome of my interest is loaded into igvShiny. I added some sessioninfo stuff as tab to the shiny which helped me to track what is going on. That's why I upload them again. 

[Scripts.zip](https://github.com/paul-shannon/igvShiny/files/8694047/Scripts.zip)

Not sure if I added something useful to your discussion, but I hope this helps. At least I can confirm again that it still works for me.

Best,
Christian

**Comment by paul-shannon** [comment] 2022-05-15 00:22
Thanks @ChristianRohde!  Nicely done.

 @JAMKuttan - could you give Christian's scripts a try?   The zip file has ```server.R``` and ```ui.R```.  You probably know this better than I, but these few lines are all that is required to run Christian's demo:
```
R> library(shiny)
R> runApp()
```

**Comment by JAMKuttan** [comment] 2022-05-17 20:23
@paul-shannon I can confirm this is working now! I have tested on my personal project as well. 


if(!dir.exists("tracks")){
  dir.create("tracks")
}
**addResourcePath("tracks", "tracks")**

@ChristianRohde was correct. Setting the resource path is what was needed. Thank you both! This was quite an error we were seeing. I am glad we got it figured out.

**Comment by paul-shannon** [comment] 2022-05-18 15:07
@JAMKuttan - very glad to hear this is working.  Our thanks to @ChristianRohde for figuring this out.

You say that you added ```addResourcePath``` to your script, and then it worked.
```addResourcePath``` is in ```customGenome-localFiles-sars.R```.  I thought that you reported you could not  get this demo script to work.   

Could you clarify, please?   I do not want to urge others to use that demo if it failed for you.

**Comment by paul-shannon** [comment] 2022-05-27 23:18
with these changes merged into the master branch, I am closing this comment - with thanks to those who helped along the way.

**Closed by paul-shannon** 2022-05-27 23:18 UTC
