### ISSUE TITLE
Questions on using the GWAS track

### ISSUE THREAD

**Issue by heimannch** [paul-shannon/igvShiny#11] opened 2021-02-09 22:31 UTC
Hi @paul-shannon! 
I am very interested in using igvShiny to display GWAS results. During my initial attempts at implementing it, I came across some initial questions/suggestions.

**1. Add GWAS track in a Shiny module**

In `igvShinyDemo-withModules.R` I found that appending a `session$ns()` in the id was enough to load the GWAS track:
```
observeEvent(input$addGwasTrackButton, {
      printf("---- addGWASTrack")
      printf("current working directory: %s", getwd())
      showGenomicRegion(session, id=session$ns("igvShiny_0"), "chr19:45,248,108-45,564,645")
      loadGwasTrack(session, id=session$ns("igvShiny_0"), trackName="gwas", tbl=tbl.gwas, deleteTracksOfSameName=FALSE)
      })
```
It is worth noting that this same change worked partially to the other tracks (a box for the track is added, but no data is displayed). We discussed about Shiny modules in the past, and I was wondering if you have any suggestions on this topic.

**2. folder /tracks** 

How do you recommend dealing with the /tracks folder that is created by the GWAS track? I see on `igvShinyDemo.R` that there is some code to create the folder, but I would be interested in making sure that this folder is cleaned after each session.

**3. GWAS track added as default at IGV start**

Is there a way to load the GWAS track as default? I imagine that it would be an argument to the `igvShiny` call at `renderIgvShiny`, but I didn't figure out how to do that. 

Thanks!

**Comment by paul-shannon** [comment] 2021-02-12 14:08
Hi Carolina,

Sorry for my delayed reply!

1. Since namespacing your widget id works for the gwas track, and not for other tracks, the problem is certainly mine to fix.  I will take a look.
2. The tracks/ directory should be, or at least should optionally  be, a temporary directory, which base R supports.  I will make that change.
3. Specifying any number, and any type of “startup” tracks, specified in the constructor, is a good idea  I will add that.

Thank you!

 - Paul

**Comment by heimannch** [comment] 2021-02-22 22:46
Hi Paul,

I had some time recently to explore in more detail the GWAS track, and the only thing that I would add to my suggestion list is a pop-over window in the points (something similar to the image in https://github.com/igvteam/igv.js/issues/1135). 

Thanks!

Carol

**Comment by paul-shannon** [comment] 2021-02-22 22:48
Will do!  I have code for that lying around somewhere.   Is Friday soon enough? 

Do you still need your own colors for the GWAS values?

 - Paul

**Comment by heimannch** [comment] 2021-02-22 23:18
Thanks for your reply! Yes, Friday is soon enough (I am with flexible deadlines, so there is no hurry on my end).

Oh, thanks for bringing the GWAS colors issue - at first, I wanted that to highlight user-selected phenotypes. But after some exploration, I discovered that we can have multiple GWAS tracks, which seems to be an even better solution for this use case.
![image](https://user-images.githubusercontent.com/32350126/108782655-d5205000-7520-11eb-8ed3-5f95b38cc957.png)

Carol

**Comment by paul-shannon** [comment] 2021-02-26 00:14
@heimannch, I just committed a small addition to igvShinyDemo.R - an event handler for the ```igv-clickTrack``` event which always fires when you click on an element in the genome browser.   Package version 1.2.17.

Here's what it looks like, on a gwas track, clicking on on snp:

![image](https://user-images.githubusercontent.com/2480712/109236244-17959700-7784-11eb-8dc0-2ca0bc5a8ad5.png)

Let me know, please, if this is headed in the right direction for you.

**Comment by heimannch** [comment] 2021-02-26 16:13
Yes, that is exactly what I had in mind - thanks!

**Comment by paul-shannon** [comment] 2021-03-05 01:06
@heimannch - Hi Carolina,

I have looked at a bunch of different ways to add extra tracks at igvShiny widget startup.  Lots of confusing and only somewhat promising strategies.   

Then it occurred to me that igvShiny.js  could simply send an event to R when it is ready, at which point your shiny app can load additional tracks, all of that occurring - in the user's experience - at widget creation time.  

For instance:
```
    observeEvent(input$igvReady, {
        containerID <- input$igvReady
        printf("igv ready, %s", containerID)
        loadBedTrack(session, id=containerID, trackName="bed.ready", tbl=tbl.bed, color="red");
        })
```
The igv.js instance know's its ID, so it returns it as data within the igvReady event.    I'll merge these changes shortly.  Could you then give it a try?

**Comment by heimannch** [comment] 2021-03-05 18:41
Hi @paul-shannon,
Your suggested approach worked, thanks! 
For reference, I had to change  `igvShiny.js` with the namespace that is being used in my Shiny module.

**Comment by paul-shannon** [comment] 2021-03-05 18:49
Glad it worked! 

Can we figure out a way to keep igvShiny.js unchanged, parameterize your namespace?

**Comment by heimannch** [comment] 2021-03-08 18:43
Hi @paul-shannon,
I just submitted a PR with a suggestion of an approach to send the namespace from the Shiny session to igvShiny. This will only take care of the events that had the namespace hardcoded in the code - ie, functions to add other tracks, such as `loadGwasTrack`, still need to have `session$ns()` appended in the `id` parameter. I think a similar approach to what is in the PR can be used to solve that issue, but I still need to figure out how.

**Comment by paul-shannon** [comment] 2021-03-16 19:42
creating a new issue for the module/namespace/div-id question

**Closed by paul-shannon** 2021-03-16 19:42 UTC
